version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: isperp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-isperp}
      MYSQL_USER: ${DB_USERNAME:-isperp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - isperp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: isperp-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-isperp}
      DB_USERNAME: ${DB_USERNAME:-isperp}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      JWT_SECRET: ${JWT_SECRET:-myVerySecureSecretKeyThatIsAtLeast256BitsLongForJWTSecurityAndMustBeAtLeast32CharactersLongToMeetTheRequirements}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - isperp-network
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: isperp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - isperp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  isperp-network:
    driver: bridge