-- ==============================================================================
-- afterMigrate.sql (EXECUTADO EXCLUSIVAMENTE NOS AMBIENTES LOCAL / DEV)
-- O seeder de homologação completo e operacional é gerenciado programaticamente
-- pelo serviço br.dev.xb.isperp.seeder.DevDataSeederService (@Profile("dev")).
-- ==============================================================================
